### ISSUE TITLE
Migration from Java processing to Flutter Processing 

### ISSUE THREAD

**Issue by baimamboukar** [matthew-carroll/flutter_processing#129] opened 2022-07-29 08:50 UTC
Hello @matthew-carroll 

What an amazing project 🎉🎉🎉
This is very interesting...

I have many projects done in Java processing... It is possible to migrate them to flutter? By using this plugin

Does it have all Java processing features?

**Comment by matthew-carroll** [comment] 2022-07-30 03:27
Hi. You can track supported APIs here: https://github.com/matthew-carroll/flutter_processing/blob/main/README_API_CHECKLIST.md

I'm going to close this ticket because it's not a bug report or a feature request.

**Closed by matthew-carroll** 2022-07-30 03:27 UTC
